dist: trusty
language: bash

env:
    global:
        - NUM_BUILDS=4
    matrix:
        - BUILD_ID=0
        - BUILD_ID=1
        - BUILD_ID=2
        - BUILD_ID=3

install:
    - git submodule update --init --recursive --remote
    - cd $TRAVIS_BUILD_DIR/scripts; ./pull_traces.sh
    - cd $TRAVIS_BUILD_DIR/scripts; ./mount_prefetchers.sh

script: 
    - $TRAVIS_BUILD_DIR/scripts/scheduler.sh $NUM_BUILDS $BUILD_ID
    - $TRAVIS_BUILD_DIR/scripts/build.sh 

