dist: trusty
language: bash

env:
    - BASEMODEL=no
    - BASEMODEL=next_line

install:
    - cd $TRAVIS_BUILD_DIR/scripts; ./mount_prefetchers.sh

scripts: "$TRAVIS_BUILD_DIR/scripts/run.sh $BASEMODEL"
