dist: trusty
language: bash

env:
    - L1_MODEL=no
    - L1_MODEL=next_line

install:
    - git submodule update --recursive --remote
    - cd $TRAVIS_BUILD_DIR/scripts; ./mount_prefetchers.sh

script: 
    - $TRAVIS_BUILD_DIR/scripts/build.sh $L1_MODEL
    - $TRAVIS_BUILD_DIR/scripts/run.sh $L1_MODEL

