dist: trusty
language: bash

before_install:
    - cd $TRAVIS_BUILD_DIR/scripts; ./mount_prefetchers.sh

install:
    - cd $TRAVIS_BUILD_DIR/scripts; ./build.sh
    - cd $TRAVIS_BUILD_DIR/scripts; ./build.sh
